### ISSUE TITLE
Work out the right architecture for the system

### ISSUE THREAD

**Issue by jonnyarnold** [reevoo/samuel#16]
This is probably an ongoing task, but I've left it here because that's what we're focusing on at the moment.

**Comment by jonnyarnold** [comment]
You can't have a pair assignment. Boo Github, boo.

**Comment by lpil** [comment]
See #11

**Comment by lpil** [comment]
Working on... fixing the data provider. Then we should do integration tests. Then we should try and get the most basic check (the guidelines) working.

**Comment by jonnyarnold** [comment]
I'm confident this is working now.
