### ISSUE TITLE
If multiple comments need to be posted as a result of a single hook, merge them into one

### ISSUE THREAD

**Issue by lpil** [reevoo/samuel#18]

**Comment by jonnyarnold** [comment]
I don't think this provides any benefit.

**Comment by lpil** [comment]
Really? It's trivial to implement, and prevents massive amounts of email spam. Having said that, we've not got anything that results in this situation yet.

**Comment by jonnyarnold** [comment]
If you're getting lots of e-mail spam from Samuel, you should really listen to it ;)

**Comment by lpil** [comment]
Everyone in the organisation will get an email per post, that's not stuff that needs to be listened to.
