### ISSUE TITLE
Use 12-factor rules

### ISSUE THREAD

**Issue by jonnyarnold** [reevoo/samuel#19]
If we go [12 Factor](http://12factor.net/), we could potentially [deploy to Heroku](https://github.com/HashNuke/heroku-buildpack-elixir). Yay.

So far I think all we need to do is to move our config to ENV variables.

**Comment by lpil** [comment]
Not interested in Heroku, but 12 factor seems like a good idea.

Configuring all the checks over ENV variables seems a bit awkward though.

**Comment by jonnyarnold** [comment]
Well that's not config for now, so let's leave that. All we have is the access token.

**Comment by jonnyarnold** [comment]
Done!

**Comment by lpil** [comment]
:dancer:
